### ISSUE TITLE
missing Fritz items?

### ISSUE THREAD

**Issue by yosun** [fritzlabs/fritz-vision-unity#1]
Assets/Scripts/FritzVisionUnity.cs(140,31): error CS0246: The type or namespace name 'FritzPose' could not be found (are you missing a using directive or an assembly reference?)

Assets/Scripts/FritzVisionUnity.cs(140,47): error CS0246: The type or namespace name 'FritzPoseParts' could not be found (are you missing a using directive or an assembly reference?)

Assets/Scripts/FritzVisionUnity.cs(31,5): error CS0246: The type or namespace name 'FritzPoseParts' could not be found (are you missing a using directive or an assembly reference?)

**Comment by ghop02** [comment]
Hi Yosun, with the latest release, we added a Fritz namespace.

`using AI.Fritz.Vision;`

should do the trick. 

Also this repo is a bit out of date, check out https://github.com/fritzlabs/fritz-unity-sdk for the latest version!
